defaults: &defaults
  app_name: "建筑同城"
  foot_html: "&copy; 建筑同城."
  app_keywords: "建筑,同城,资质,认证,挂靠,代办,转让,简历,培训,招聘,公司,猎头,个人,jzcnw,jianzhu"
  app_description: "建筑同城网是一个建筑企业与人才交流的中立平台."  
  domain: "127.0.0.1:3000"
  admin_emails:
    - "admin@admin.com"
  google_analytics_key: ""
  upload_url: "http://ruby-china-files-dev.b0.upaiyun.com"
  upyun_username: "test"
  upyun_password: "123123"
  upyun_bucket: "ruby-china-files-dev"
  google_group_email: "shanghaionrails@googlegroups.com"
  email_sender: 'no-reply@ruby-china.org'
  aws_access_key_id: ''
  aws_secret_access_key: ''
  faye_server: "http://127.0.0.1:8080/faye"
  faye_token: "123456"
  twitter_token: "uJ9fBa53SmqrHBqs1qq5cg"
  twitter_secret: "b9e9hbsa9sYYCqmW0kTyfALshclmkQX4kzTm8BBBTw"
  github_token: "207bd3415f6f42bcf8da"
  github_secret: "8d51636e1325cd4a0af78efe567a35f29d42096d"
  douban_token: "04fab3198986e6350ef0194c9c94b29f"
  douban_secret: "5c08eac53cfa1890"
  google_js_api_key: "ABQIAAAAC-ble-vmy_g7-Qvem5P86xTX2XchcwgyHzp4Xo0DHRAzt2aLjhQnflwIyCJBOWYCE_rFuUkE0qEmhw"
  google_custom_search_id: "016658237367474087615:WMX464284035"
  external_feed_url: "http://ruby-taiwan.org/topics/feed"
  external_feed_name: "Ruby Taiwan Group"
  twitter_id: "ruby_china"
  gravatar_proxy: "http://ruby-china.org"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults